project:
  type: website

website:
  reader-mode: true
  title: "Psychology As A Science"
  navbar:
    background: primary
    right:
      - href: handouts.qmd
        text: Lecture handouts
      - href: slides.qmd
        text: Lecture slides

format:
  html:
    template-partials:
      - title-metadata.html
    theme: cosmo
    css: styles.css


